language: generic
sudo: required
before_install:
- ".travis/before_install.sh"
script:
- ".travis/script.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
after_failure:
- ".travis/after_failure.sh"
matrix:
  include:
  - name: Linux with Defaults against GCC Network and Service Tests
    os: linux
    compiler: gcc
    env: BUILD_TARGET="linux-auto-gcc-check-happy" TRAVIS_TAG="true"
deploy:
  provider: gcs
  access_key_id: GOOGNPZYTVTEPZM5VBRAVVUU
  secret_access_key:
    secure: HH/3FOuU8M4AG9Gdwjs52yw2L1JnAvupcLbFurJtrfqfspXYj/1JKTbGjbmVcb6jS/mK9pNPCs2q/L111JeufWa5cR8RAw49CZ9ENqUHs0t7FV0vgk2h7O+QrQVDCQqN9XvgTGpe071IFJOPCpASRYTT1NT6wqEFyPyCl6b+eU8RLXkRwSQrd2heAdKlD/sHBda3AA9OE8AnKRdY5ZKLhtAt2xl9z4w6vWi1MTbmoRVZaCZaAjmtM5OmRAbqTz4kO41Zy57u1350uEiuOV6l/1QVpfd8zk3iYMC4T5OGrDVzk53WejnHa+Ne1nanswW6HBnsrunBcJV3KWSx2O3mdKBsBunJ4t+gjYAtYaPdMIqqvswXXN95d6VOayTvFBJfmcPLNz4h4ypDf9wYBrSdCpnHWTJh8lmgC2vd8k2tvy/67OgVlYUUX5X+cOkLZI4cfVwOrx2wFIYvxcbsh1LyUQ/EE97QOuftcgnI654u/VLJXuPK9lTj3tEDlH27Hz7h8aJ/dpsOTTCC4t0AqAiXaU7S4HO7B3WnQf4ObVzUCcIQLeqHAlzg+BcOCgy+Jvrqrq4A1PB10YAdwIWjBtIZ2fEuuCCFNCcE9rMp5ddnc3sVVX+NEfDm+O9HeNRvg2VRTWq4Bm5sBSjzJ+SDP5bK9BQrSoXwiqDRM+AGheB1B1w=
  bucket: openweave
  skip_cleanup: true
  acl: public-read
  upload-dir: happy-test-log/$TRAVIS_BUILD_NUMBER
  local-dir: "$TRAVIS_BUILD_DIR/happy-test-logs"
  on:
    repo: openweave/openweave-core
    tags: true
env:
  global:
    secure: FTcSFD+dWmpkDUKMCvNVg8dyZPFx91AljrWe6bT4vvEdFZs7ZGJz1VIEHXqLhDfF7igh5iXvXQ/pQKUWyctGEU0VrfGgeZB+szojOMn5NFKhWtZdNeqNn9SvBSko1/ToE/J1yg6GWVnERScL1lGaWjPPKr9O1uBYt7tqHl98jq6t4c/pX78Eisy85WlzVn9UpKC5XyaNjaGyhoHjt0zWQfb3pKcWCZd6rl2LCesCKL4UVhwWAUg0GCiTR98iIUjmEt6QLvSIiphTrbbEd/na+O+RbSUa9SG5Jk2KiAwfLTiGaIfZzltYEOX/i32CEzXTCJW9V0Fg9tujFipZwg+v0b2TDUW4hc+orYM+4NNkcyQmpS+GMP1HZfYz3FRtZAZ2Q39WNEpLU+0fdSoZL8MZC2DT7V9mIyuALxuZmZapOqbq1/OMO1s7LwqpR0J1lCGFAw8xV3ek24fkyqxghZhC/rOR9o+a5kn/2KT6lSZtfLTtXp0toOfZ/nGytCvFOm60RLj46Tz4iyoK/oQLV/F3r4tCyP/hfkec2GU+2++Dw1v3WJu9egrxAEEaW1jGWzZ5mr86waeBcFqFHy6wU2Nc7rckHeoMOoWgTF8qiyLT6muPDSfCbyu9G9PJQNPbIfso8GE1tibNPltOQKThI5cGcwYfB1tLa3GDvhRdC5prHDs=
